export const SET_PRODUCTS = 'SET_PURCHASE_PRODUCTS';
export const SET_ITEMS = 'SET_PURCHASE_ITEMS';
export const SET_LOADING = 'PURCHASE_SET_LOADING';
export const UNSET_LOADING = 'PURCHASE_UNSET_LOADING';
export const SET_PAYING = 'PURCHASE_SET_PAYING';
export const SET_SUCCESS = 'PURCHASE_SET_SUCCESS';
export const SET_FAIL = 'PURCHASE_UNSET_FAIL';
